const express = require('express');
const { getAssociatedTicket, createNote, markBriefSubmitted, uploadFile, getDeal } = require('../hubspot');
const { generateMockupImage } = require('../lib/gemini');

const router = express.Router();

// Build HTML note body for deal + ticket timelines
function buildNoteHtml(f) {
  const links = (urls) =>
    urls.map((u) => `<a href="${u}">${decodeURIComponent(u.split('/').pop())}</a>`).join('<br>');

  return `
<h2>Design Brief Submission</h2>

<h3>Design Vision</h3>
<p><strong>Description:</strong><br>${f.designDescription}</p>
${f.referenceInspiration ? `<p><strong>Reference / Inspiration:</strong><br>${f.referenceInspiration}</p>` : ''}

<h3>Colors</h3>
<p><strong>Pantone / Color Values:</strong><br>${f.pantoneColors || '—'}</p>

<h3>Typography</h3>
<p><strong>Preferred Font(s):</strong> ${f.fontNames || '—'}</p>
${f.fontFileUrls.length ? `<p><strong>Font Files:</strong><br>${links(f.fontFileUrls)}</p>` : ''}

<h3>Design Files</h3>
${f.designFileUrls.length ? `<p>${links(f.designFileUrls)}</p>` : '<p>No design files uploaded.</p>'}
${f.fileDescription ? `<p><strong>File Notes:</strong><br>${f.fileDescription}</p>` : ''}
  `.trim();
}

// Normalize an incoming value to an array of strings
function toArray(val) {
  if (Array.isArray(val)) return val.filter(Boolean);
  if (val) return [val];
  return [];
}

/**
 * Background job: generate a Gemini concept image and post it as a
 * second internal note on the ticket. Runs after the response is sent —
 * any failure here is logged only and does not affect the customer.
 */
async function generateAndPostMockup({ dealId, ticketId, f, dealData }) {
  const imageBuffer = await generateMockupImage({
    cupType:     dealData.cupType,
    brandName:   dealData.brandName,
    description: f.designDescription,
    colors:      f.pantoneColors,
    wrapStyle:   f.wrapStyle,
  });

  const imageUrl = await uploadFile(imageBuffer, 'ai-concept.jpg', 'image/jpeg');

  const noteHtml = `
<h2>AI Concept Image</h2>
<p><em>Generated by Gemini Imagen based on the design brief. For designer reference only — not a production asset.</em></p>
<img src="${imageUrl}" style="max-width:100%;border-radius:6px;" />
<p><a href="${imageUrl}">Download full image</a></p>
  `.trim();

  await createNote(dealId, ticketId, noteHtml);
}

// POST /submit
// Body (JSON): dealId + all brief fields + pre-uploaded file URL arrays
router.post('/', async (req, res) => {
  try {
    const {
      dealId,
      designDescription,
      referenceInspiration,
      pantoneColors,
      fontNames,
      fontFileUrls,
      designFileUrls,
      fileDescription,
      wrapStyle,
    } = req.body;

    if (!dealId)            return res.status(400).json({ error: 'dealId is required.' });
    if (!designDescription) return res.status(400).json({ error: 'Design description is required.' });

    const f = {
      designDescription,
      referenceInspiration: referenceInspiration || '',
      pantoneColors:        pantoneColors || '',
      fontNames:            fontNames || '',
      fontFileUrls:         toArray(fontFileUrls),
      designFileUrls:       toArray(designFileUrls),
      fileDescription:      fileDescription || '',
      wrapStyle:            wrapStyle || '',
    };

    // 1. Fetch deal data (needed for Gemini prompt context)
    const dealData = await getDeal(dealId);

    // 2. Find the existing ticket associated to this deal
    const ticketId = await getAssociatedTicket(dealId);

    // 3. Post the brief as an internal note on the ticket + deal timelines
    await createNote(dealId, ticketId, buildNoteHtml(f));

    // 4. Flag deal as submitted to prevent duplicates
    await markBriefSubmitted(dealId);

    // 5. Send success to customer immediately — they're done
    res.json({ success: true, ticketId });

    // 6. Fire Gemini concept image generation in the background (non-blocking)
    if (process.env.GEMINI_API_KEY) {
      setImmediate(() =>
        generateAndPostMockup({ dealId, ticketId, f, dealData })
          .catch((err) => console.error('[Gemini] Mockup generation failed:', err.message))
      );
    }

  } catch (err) {
    console.error('Submit error:', err.response?.data || err.message);
    res.status(500).json({ error: 'Submission failed. Please try again.' });
  }
});

module.exports = router;
